✨ Sync from SuzuBlog main branch

diff --git a/.github/workflows/target-branch-check.yml b/.github/workflows/target-branch-check.yml
--- a/.github/workflows/target-branch-check.yml
+++ b/.github/workflows/target-branch-check.yml
@@ -3,15 +3,21 @@ name: Check Target Branch
 on:
   pull_request:
     branches:
-      - main
-      - blog
+      - '**'
 
 jobs:
   check_branch:
     runs-on: ubuntu-latest
     steps:
       - name: Check PR target
-        if: github.base_ref == 'main' || github.base_ref == 'blog'
         run: |
-          echo "::error::This PR targets the wrong branch (${github.base_ref}). Please change the target branch to 'dev'."
-          exit 1
+          if [[ "${{ github.actor }}" == "ZL-Asica" ]]; then
+            exit 0
+          fi
+
+          if [[ "${{ github.event.pull_request.base.ref }}" == "main" || "${{ github.event.pull_request.base.ref }}" == "blog" ]]; then
+            echo "::error::This PR targets the wrong branch (${ {github.event.pull_request.base.ref} }). Please change the target branch to 'dev'."
+            exit 1
+          else
+            echo "Target branch is valid (${ {github.event.pull_request.base.ref} })."
+          fi
